import BlogCategories from './BlogCategories'
import Hero from './Hero'
import Partners from './Partners'
import Probiotic from './Probiotic'
import ProbioticContent from './ProbioticContent'
import ProbioticDesktopTabs from './ProbioticDesktopTabs'
import ProbioticMobileTabs from './ProbioticMobileTabs'
import Products from './Products'
import ProductsSlider from './ProductsSlider'
import QaSlider from './QaSlider'
import Videos from './Videos'

export { BlogCategories }
export { Hero }
export { Partners }
export { Probiotic }
export { ProbioticContent }
export { ProbioticDesktopTabs }
export { ProbioticMobileTabs }
export { Products }
export { ProductsSlider }
export { QaSlider }
export { Videos }
